title: Victor Art and Design
logo: doc/assets/WhatsApp Image 2024-09-11 at 15.16.45_bbc799dd.png
description: We've got you covered
#show_downloads: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
